#ifndef TEST_CONFIGURATION_H
#define TEST_CONFIGURATION_H

// std/container/fixed
// #define TEST_CONTAINER_FIXED_BASE
// #define TEST_CONTAINER_FIXED_ARRAY

// std/container/dynamic
// #define TEST_CONTAINER_DYNAMIC_BASE
// #define TEST_CONTAINER_DYNAMIC_VECTOR
// #define TEST_CONTAINER_DYNAMIC_SET
// #define TEST_CONTAINER_DYNAMIC_MAP

// std/memory
// #define TEST_MEMORY_SMART_PTR_BASE
// #define TEST_MEMORY_SMART_PTR_UNIQUE_PTR
// #define TEST_MEMORY_SMART_PTR_SHARED_PTR

// std/functional
// #define TEST_FUNCTIONAL_CALLABLE_GLOBAL
// #define TEST_FUNCTIONAL_CALLABLE_MEMBER

// std/utility
// #define TEST_UTILITY_PAIR

#endif